.\" (C) Copyright 2017 Colby Connolly <protheophage@gmail.com>,
.\"
.TH AIC "1" "User Commands"
.SH NAME
aic \- Automated Image Collector
.SH SYNOPSIS
.B aic
.SH DESCRIPTION
.PP
	Finds all storage devices attached to the computer, and forensically images them to the "flag" directory "uunique_dirrr_nammme" on a destination device.

	This tool was designed to be used with a live Linux distribution. In order for this tool to function properly, the destination device must have a directory named "uunique_dirrr_nammme" located in the root directory.

	This tool was created with and tested on Kali Linux.

	This tool has been tested, and found to create images in a forensically sound manner. This means that:
	1)All devices, excluding the destination device, are mounted in a read only state.
	2)None of the files are altered from their original state.
	3)The created images are created in a raw/dd format.
	4)The input device and output images are hashed for integrity.

.SH OPTIONS
This program asks for some user input when started.
.SH CREDITS
This tool uses the following programs to accomplish the desired tasks:
UMOUNT FDISK GREP MKDIR ECHO MOUNT HEAD TAIL FIND READ SED
For information about these tools please see the appropriate manual pages (i.e. man umount)
.SH AUTHOR
Written by Colby Connolly
.SH "REPORTING BUGS"
protheophage@gmail.com
.SH COPYRIGHT
Copyright \(co 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
.br
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
.SH "SEE ALSO"
Full documentation at: <http://www.gnu.org/software/coreutils/ls>
.br
or available locally via: info \(aq(coreutils) ls invocation\(aq

